const vocabularyData = [
    // --- ALLGEMEIN ---
    { "id": 1, "category": "Allgemein", "german": "Krankenhaus", "type": "Das Nomen", "turkish": "Hastane", "example": "Das Krankenhaus ist in der Nähe." },
    { "id": 2, "category": "Allgemein", "german": "Notaufnahme", "type": "Die Nomen", "turkish": "Acil Servis", "example": "Bringen Sie ihn sofort in die Notaufnahme!" },
    { "id": 3, "category": "Allgemein", "german": "Station", "type": "Die Nomen", "turkish": "Servis / Bölüm", "example": "Er liegt auf der kardiologischen Station." },
    { "id": 4, "category": "Allgemein", "german": "Patient", "type": "Der Nomen", "turkish": "Hasta", "example": "Der Patient schläft noch." },
    { "id": 5, "category": "Allgemein", "german": "Arzt", "type": "Der Nomen", "turkish": "Doktor", "example": "Der Arzt kommt gleich zur Visite." },
    { "id": 6, "category": "Allgemein", "german": "Visite", "type": "Die Nomen", "turkish": "Doktor Viziti", "example": "Die Visite beginnt um 8 Uhr." },
    { "id": 7, "category": "Allgemein", "german": "Diagnose", "type": "Die Nomen", "turkish": "Teşhis", "example": "Die Diagnose ist noch nicht sicher." },
    { "id": 8, "category": "Allgemein", "german": "Rezept", "type": "Das Nomen", "turkish": "Reçete", "example": "Ich schreibe Ihnen ein Rezept auf." },
    { "id": 9, "category": "Allgemein", "german": "Behandlung", "type": "Die Nomen", "turkish": "Tedavi", "example": "Die Behandlung dauert zwei Wochen." },
    { "id": 10, "category": "Allgemein", "german": "Untersuchung", "type": "Die Nomen", "turkish": "Muayene", "example": "Die Untersuchung war schmerzlos." },
    { "id": 11, "category": "Allgemein", "german": "Überweisung", "type": "Die Nomen", "turkish": "Sevk", "example": "Sie brauchen eine Überweisung." },
    { "id": 12, "category": "Allgemein", "german": "Entlassung", "type": "Die Nomen", "turkish": "Taburcu olma", "example": "Die Entlassung ist für morgen geplant." },
    { "id": 13, "category": "Allgemein", "german": "Aufnahme", "type": "Die Nomen", "turkish": "Kayıt / Kabul", "example": "Bitte gehen Sie zuerst zur Aufnahme." },
    { "id": 14, "category": "Allgemein", "german": "Labor", "type": "Das Nomen", "turkish": "Laboratuvar", "example": "Die Proben sind bereits im Labor." },
    { "id": 15, "category": "Allgemein", "german": "Krankenkasse", "type": "Die Nomen", "turkish": "Sağlık Sigortası", "example": "Haben Sie Ihre Krankenkassenkarte dabei?" },
    
    // --- ANATOMIE ---
    { "id": 16, "category": "Anatomie", "german": "Herz", "type": "Das Nomen", "turkish": "Kalp", "example": "Das Herz schlägt schnell." },
    { "id": 17, "category": "Anatomie", "german": "Lunge", "type": "Die Nomen", "turkish": "Akciğer", "example": "Atmen Sie tief in die Lunge ein." },
    { "id": 18, "category": "Anatomie", "german": "Gehirn", "type": "Das Nomen", "turkish": "Beyin", "example": "Das Gehirn ist sehr komplex." },
    { "id": 19, "category": "Anatomie", "german": "Magen", "type": "Der Nomen", "turkish": "Mide", "example": "Ich habe Schmerzen im Magen." },
    { "id": 20, "category": "Anatomie", "german": "Leber", "type": "Die Nomen", "turkish": "Karaciğer", "example": "Alkohol schadet der Leber." },
    { "id": 21, "category": "Anatomie", "german": "Niere", "type": "Die Nomen", "turkish": "Böbrek", "example": "Der Patient has Nierenschmerzen." },
    { "id": 22, "category": "Anatomie", "german": "Blut", "type": "Das Nomen", "turkish": "Kan", "example": "Wir brauchen eine Blutprobe." },
    { "id": 23, "category": "Anatomie", "german": "Knochen", "type": "Der Nomen", "turkish": "Kemik", "example": "Der Knochen ist gebrochen." },
    { "id": 24, "category": "Anatomie", "german": "Haut", "type": "Die Nomen", "turkish": "Cilt", "example": "Die Haut ist gerötet." },
    { "id": 25, "category": "Anatomie", "german": "Ader", "type": "Die Nomen", "turkish": "Damar / Ven", "example": "Ich finde keine gute Ader." },
    { "id": 26, "category": "Anatomie", "german": "Wirbelsäule", "type": "Die Nomen", "turkish": "Omurga", "example": "Er hat Probleme mit der Wirbelsäule." },
    { "id": 27, "category": "Anatomie", "german": "Gelenk", "type": "Das Nomen", "turkish": "Eklem", "example": "Das Kniegelenk ist geschwollen." },
    { "id": 28, "category": "Anatomie", "german": "Muskel", "type": "Der Nomen", "turkish": "Kas", "example": "Ich habe einen Muskelkater." },
    { "id": 29, "category": "Anatomie", "german": "Nerv", "type": "Der Nomen", "turkish": "Sinir", "example": "Ein Nerv ist eingeklemmt." },
    { "id": 30, "category": "Anatomie", "german": "Bauch", "type": "Der Nomen", "turkish": "Karın", "example": "Der Bauch ist weich." },

    // --- AKTION ---
    { "id": 31, "category": "Aktion", "german": "Messen", "type": "Das Verb", "turkish": "Ölçmek", "example": "Ich messe jetzt das Fieber." },
    { "id": 32, "category": "Aktion", "german": "Spritzen", "type": "Das Verb", "turkish": "İğne yapmak", "example": "Soll ich das Insulin spritzen?" },
    { "id": 33, "category": "Aktion", "german": "Verbinden", "type": "Das Verb", "turkish": "Sarmak / Pansuman", "example": "Ich muss die Wunde neu verbinden." },
    { "id": 34, "category": "Aktion", "german": "Waschen", "type": "Das Verb", "turkish": "Yıkamak", "example": "Soll ich Ihnen beim Waschen helfen?" },
    { "id": 35, "category": "Aktion", "german": "Füttern", "type": "Das Verb", "turkish": "Beslemek", "example": "Ich muss den Patienten füttern." },
    { "id": 36, "category": "Aktion", "german": "Lagern", "type": "Das Verb", "turkish": "Pozisyon vermek", "example": "Wir müssen den Patienten lagern." },
    { "id": 37, "category": "Aktion", "german": "Mobilisieren", "type": "Das Verb", "turkish": "Hareket ettirmek", "example": "Wir wollen den Patienten heute mobilisieren." },
    { "id": 38, "category": "Aktion", "german": "Dokumentieren", "type": "Das Verb", "turkish": "Kaydetmek", "example": "Ich muss die Werte dokumentieren." },
    { "id": 39, "category": "Aktion", "german": "Desinfizieren", "type": "Das Verb", "turkish": "Dezenfekte etmek", "example": "Bitte die Hände desinfizieren." },
    { "id": 40, "category": "Aktion", "german": "Absaugen", "type": "Das Verb", "turkish": "Aspire etmek", "example": "Ich muss den Schleim absaugen." },

    // --- SYMPTOME ---
    { "id": 41, "category": "Symptome", "german": "Schmerz", "type": "Der Nomen", "turkish": "Ağrı", "example": "Wo genau haben Sie Schmerzen?" },
    { "id": 42, "category": "Symptome", "german": "Fieber", "type": "Das Nomen", "turkish": "Ateş", "example": "Das Fieber sinkt langsam." },
    { "id": 43, "category": "Symptome", "german": "Husten", "type": "Der Nomen", "turkish": "Öksürük", "example": "Haben Sie trockenen Husten?" },
    { "id": 44, "category": "Symptome", "german": "Übelkeit", "type": "Die Nomen", "turkish": "Bulantı", "example": "Ist Ihnen übel?" },
    { "id": 45, "category": "Symptome", "german": "Schwindel", "type": "Der Nomen", "turkish": "Baş dönmesi", "example": "Ich habe Schwindelgefühle." },
    { "id": 46, "category": "Symptome", "german": "Atemnot", "type": "Die Nomen", "turkish": "Nefes darlığı", "example": "Haben Sie Atemnot beim Gehen?" },
    { "id": 47, "category": "Symptome", "german": "Erbrechen", "type": "Das Nomen", "turkish": "Kusma", "example": "Der Patient leidet unter Erbrechen." },
    { "id": 48, "category": "Symptome", "german": "Durchfall", "type": "Der Nomen", "turkish": "İshal", "example": "Seit wann haben Sie Durchfall?" },
    { "id": 49, "category": "Symptome", "german": "Verstopfung", "type": "Die Nomen", "turkish": "Kabızlık", "example": "Leiden Sie unter Verstopfung?" },
    { "id": 50, "category": "Symptome", "german": "Blutung", "type": "Die Nomen", "turkish": "Kanama", "example": "Die Blutung hat aufgehört." },

    // --- AUSRÜSTUNG ---
    { "id": 51, "category": "Ausrüstung", "german": "Blutdruckmessgerät", "type": "Das Nomen", "turkish": "Tansiyon aleti", "example": "Das Blutdruckmessgerät ist kaputt." },
    { "id": 52, "category": "Ausrüstung", "german": "Stethoskop", "type": "Das Nomen", "turkish": "Stetoskop", "example": "Ich brauche ein Stethoskop." },
    { "id": 53, "category": "Ausrüstung", "german": "Spritze", "type": "Die Nomen", "turkish": "Şırınga", "example": "Geben Sie mir eine 5ml Spritze." },
    { "id": 54, "category": "Ausrüstung", "german": "Rollstuhl", "type": "Der Nomen", "turkish": "Tekerlekli sandalye", "example": "Bitte bringen Sie einen Rollstuhl." },
    { "id": 55, "category": "Ausrüstung", "german": "Gehstützen", "type": "Die Nomen", "turkish": "Koltuk değneği", "example": "Er braucht Gehstützen." },
    { "id": 56, "category": "Ausrüstung", "german": "Infusionsständer", "type": "Der Nomen", "turkish": "Serum askısı", "example": "Der Infusionsständer wackelt." },
    { "id": 57, "category": "Ausrüstung", "german": "Thermometer", "type": "Das Nomen", "turkish": "Ateşölçer", "example": "Haben Sie ein Thermometer?" },
    { "id": 58, "category": "Ausrüstung", "german": "Verband", "type": "Der Nomen", "turkish": "Sargı", "example": "Der Verband ist nass." },
    { "id": 59, "category": "Ausrüstung", "german": "Handschuhe", "type": "Die Nomen", "turkish": "Eldiven", "example": "Ich trage Einmalhandschuhe." },
    { "id": 60, "category": "Ausrüstung", "german": "Pflaster", "type": "Das Nomen", "turkish": "Yara bandı", "example": "Ein kleines Pflaster reicht." },
    { "id": 61, "category": "Ausrüstung", "german": "Bettpfanne", "type": "Die Nomen", "turkish": "Sürgü / Ördek", "example": "Der Patient braucht die Bettpfanne." },
    { "id": 62, "category": "Ausrüstung", "german": "Katheter", "type": "Der Nomen", "turkish": "Kateter", "example": "Der Katheter muss geleert werden." },
    { "id": 63, "category": "Ausrüstung", "german": "EKG-Gerät", "type": "Das Nomen", "turkish": "EKG cihazı", "example": "Schließen Sie das EKG-Gerät an." },
    { "id": 64, "category": "Ausrüstung", "german": "Sauerstoffmaske", "type": "Die Nomen", "turkish": "Oksijen Maskesi", "example": "Wir legen die Sauerstoffmaske an." },
    { "id": 65, "category": "Ausrüstung", "german": "Defibrillator", "type": "Der Nomen", "turkish": "Defibrilatör", "example": "Bringt den Defibrillator mit!" },

    // --- PERSONAL ---
    { "id": 66, "category": "Personal", "german": "Pflegefachkraft", "type": "Die Nomen", "turkish": "Hemşire", "example": "Ich bin heute Ihre Pflegefachkraft." },
    { "id": 67, "category": "Personal", "german": "Oberarzt", "type": "Der Nomen", "turkish": "Uzman doktor", "example": "Der Oberarzt macht heute Dienst." },
    { "id": 68, "category": "Personal", "german": "Chefarzt", "type": "Der Nomen", "turkish": "Başhekim", "example": "Der Chefarzt ist im Operationssaal." },
    { "id": 69, "category": "Personal", "german": "Stationsleitung", "type": "Die Nomen", "turkish": "Servis sorumlusu", "example": "Sprechen Sie mit der Stationsleitung." },
    { "id": 70, "category": "Personal", "german": "Physiotherapeut", "type": "Der Nomen", "turkish": "Fizyoterapist", "example": "Der Physiotherapeut kommt um 10 Uhr." },
    { "id": 71, "category": "Personal", "german": "Logopäde", "type": "Der Nomen", "turkish": "Konuşma terapisti", "example": "Der Logopäde hilft beim Schlucken." },
    { "id": 72, "category": "Personal", "german": "Hebamme", "type": "Die Nomen", "turkish": "Ebe", "example": "Die Hebamme ist im Kreißsaal." },
    { "id": 73, "category": "Personal", "german": "Auszubildende", "type": "Die Nomen", "turkish": "Stajyer", "example": "Unsere Auszubildende hilft Ihnen." },
    { "id": 74, "category": "Personal", "german": "Reinigungskraft", "type": "Die Nomen", "turkish": "Temizlik görevlisi", "example": "Die Reinigungskraft kommt in Kürze." },
    { "id": 75, "category": "Personal", "german": "Rettungssanitäter", "type": "Der Nomen", "turkish": "Paramedik", "example": "Die Rettungssanitäter sind da." },

    // --- MEDIKAMENTE ---
    { "id": 76, "category": "Medikamente", "german": "Schmerzmittel", "type": "Das Nomen", "turkish": "Ağrı kesici", "example": "Brauchen Sie noch ein Schmerzmittel?" },
    { "id": 77, "category": "Medikamente", "german": "Antibiotikum", "type": "Das Nomen", "turkish": "Antibiyotik", "example": "Sie müssen das Antibiotikum zu Ende nehmen." },
    { "id": 78, "category": "Medikamente", "german": "Schlaftablette", "type": "Die Nomen", "turkish": "Uyku ilacı", "example": "Hier ist Ihre Schlaftablette." },
    { "id": 79, "category": "Medikamente", "german": "Salbe", "type": "Die Nomen", "turkish": "Merhem", "example": "Tragen Sie diese Salbe zweimal täglich auf." },
    { "id": 80, "category": "Medikamente", "german": "Tropfen", "type": "Die Nomen", "turkish": "Damla", "example": "Nehmen Sie 20 Tropfen vor dem Essen." },
    { "id": 81, "category": "Medikamente", "german": "Zäpfchen", "type": "Das Nomen", "turkish": "Fitil", "example": "Das Zäpfchen ist gegen das Fieber." },
    { "id": 82, "category": "Medikamente", "german": "Infusion", "type": "Die Nomen", "turkish": "Serum", "example": "Die Infusion läuft noch." },
    { "id": 83, "category": "Medikamente", "german": "Nebenwirkung", "type": "Die Nomen", "turkish": "Yan etki", "example": "Haben Sie Nebenwirkungen bemerkt?" },
    { "id": 84, "category": "Medikamente", "german": "Dosierung", "type": "Die Nomen", "turkish": "Doz", "example": "Die Dosierung wurde geändert." },
    { "id": 85, "category": "Medikamente", "german": "Beruhigungsmittel", "type": "Das Nomen", "turkish": "Sakinleştirici", "example": "Er hat ein Beruhigungsmittel genommen." },

    // --- NOTFALL ---
    { "id": 86, "category": "Notfall", "german": "Bewusstlos", "type": "Adjektiv", "turkish": "Bilinci kapalı", "example": "Der Patient ist bewusstlos." },
    { "id": 87, "category": "Notfall", "german": "Wiederbelebung", "type": "Die Nomen", "turkish": "Kalp masajı / CPR", "example": "Wir beginnen mit der Wiederbelebung." },
    { "id": 88, "category": "Notfall", "german": "Koma", "type": "Das Nomen", "turkish": "Koma", "example": "Er liegt im künstlichen Koma." },
    { "id": 89, "category": "Notfall", "german": "Erste Hilfe", "type": "Die Nomen", "turkish": "İlk Yardım", "example": "Erste Hilfe ist hier sehr wichtig." },
    { "id": 90, "category": "Notfall", "german": "Herzstillstand", "type": "Der Nomen", "turkish": "Kalp durması", "example": "Er hatte einen Herzstillstand." },
    { "id": 91, "category": "Notfall", "german": "Schock", "type": "Der Nomen", "turkish": "Şok", "example": "Der Patient steht unter Schock." },
    { "id": 92, "category": "Notfall", "german": "Verletzung", "type": "Die Nomen", "turkish": "Yaralanma", "example": "Die Verletzung ist schwer." },
    { "id": 93, "category": "Notfall", "german": "Wunde", "type": "Die Nomen", "turkish": "Yara", "example": "Die Wunde blutet stark." },
    { "id": 94, "category": "Notfall", "german": "Verbrennung", "type": "Die Nomen", "turkish": "Yanık", "example": "Er hat eine Verbrennung dritten Grades." },
    { "id": 95, "category": "Notfall", "german": "Notarzt", "type": "Der Nomen", "turkish": "Acil Doktoru", "example": "Rufen Sie sofort den Notarzt!" },

    // --- KRANKHEITEN ---
    { "id": 96, "category": "Krankheiten", "german": "Krebs", "type": "Der Nomen", "turkish": "Kanser", "example": "Er wird wegen Krebs behandelt." },
    { "id": 97, "category": "Krankheiten", "german": "Diabetes", "type": "Die Nomen", "turkish": "Şeker Hastalığı", "example": "Sie hat Diabetes Typ 2." },
    { "id": 98, "category": "Krankheiten", "german": "Asthma", "type": "Das Nomen", "turkish": "Astım", "example": "Er benutzt sein Asthma-Spray." },
    { "id": 99, "category": "Krankheiten", "german": "Bluthochdruck", "type": "Der Nomen", "turkish": "Yüksek Tansiyon", "example": "Bluthochdruck ist gefährlich." },
    { "id": 100, "category": "Krankheiten", "german": "Schlaganfall", "type": "Der Nomen", "turkish": "İnme / Felç", "example": "Verdacht auf Schlaganfall." },
    { "id": 101, "category": "Krankheiten", "german": "Herzinfarkt", "type": "Der Nomen", "turkish": "Kalp Krizi", "example": "Er hatte einen leichten Herzinfarkt." },
    { "id": 102, "category": "Krankheiten", "german": "Grippe", "type": "Die Nomen", "turkish": "Grip", "example": "Die Grippe ist dieses Jahr sehr stark." },
    { "id": 103, "category": "Krankheiten", "german": "Entzündung", "type": "Die Nomen", "turkish": "İltihap / Enfeksiyon", "example": "Das ist eine bakterielle Entzündung." },
    { "id": 104, "category": "Krankheiten", "german": "Allergie", "type": "Die Nomen", "turkish": "Alerji", "example": "Haben Sie eine Allergie gegen Nüsse?" },
    { "id": 105, "category": "Krankheiten", "german": "Demenz", "type": "Die Nomen", "turkish": "Demans / Bunama", "example": "Der Patient leidet an Demenz." },

    // --- DIALOGE ---
    { "id": 106, "category": "Dialoge", "german": "Wie geht es Ihnen?", "type": "Satz", "turkish": "Nasılsınız?", "example": "Guten Morgen, wie geht es Ihnen?" },
    { "id": 107, "category": "Dialoge", "german": "Haben Sie Schmerzen?", "type": "Satz", "turkish": "Ağrınız var mı?", "example": "Sagen Sie mir, haben Sie Schmerzen?" },
    { "id": 108, "category": "Dialoge", "german": "Ich bringe Ihnen die Medikamente.", "type": "Satz", "turkish": "Size ilaçları getiriyorum.", "example": "Hier sind Ihre Tabletten." },
    { "id": 109, "category": "Dialoge", "german": "Können Sie mich verstehen?", "type": "Satz", "turkish": "Beni anlayabiliyor musunuz?", "example": "Hallo, können Sie mich verstehen?" },
    { "id": 110, "category": "Dialoge", "german": "Drücken Sie die Klingel.", "type": "Satz", "turkish": "Zile basın.", "example": "Wenn etwas passiert, klingeln Sie bitte." },
    { "id": 111, "category": "Dialoge", "german": "Haben Sie gut geschlafen?", "type": "Satz", "turkish": "İyi uyudunuz mu?", "example": "Guten Tag, haben Sie gut geschlafen?" },
    { "id": 112, "category": "Dialoge", "german": "Ich helfe Ihnen beim Aufstehen.", "type": "Satz", "turkish": "Ayağa kalkmanıza yardım edeyim.", "example": "Ich helfe Ihnen." },
    { "id": 113, "category": "Dialoge", "german": "Möchten Sie etwas trinken?", "type": "Satz", "turkish": "Bir şey içmek ister misiniz?", "example": "Hier ist Wasser, möchten Sie etwas trinken?" },
    { "id": 114, "category": "Dialoge", "german": "Ich werde jetzt Ihren Blutdruck messen.", "type": "Satz", "turkish": "Şimdi tansiyonunuzu ölçeceğim.", "example": "Halten Sie Ihren Arm ruhig." },
    { "id": 115, "category": "Dialoge", "german": "Warten Sie einen Moment.", "type": "Satz", "turkish": "Bir dakika bekleyin.", "example": "Ich bin gleich wieder da." },
    { "id": 116, "category": "Dialoge", "german": "Der Arzt kommt gleich.", "type": "Satz", "turkish": "Doktor birazdan geliyor.", "example": "Bitte gedulden Sie sich einen Moment." },
    { "id": 117, "category": "Dialoge", "german": "Haben Sie Allergien?", "type": "Satz", "turkish": "Alerjiniz var mı?", "example": "Haben Sie Allergien gegen Penicillin?" },
    { "id": 118, "category": "Dialoge", "german": "Gute Besserung!", "type": "Satz", "turkish": "Geçmiş olsun!", "example": "Auf Wiedersehen und gute Besserung!" },
    { "id": 119, "category": "Dialoge", "german": "Soll ich das Fenster schließen?", "type": "Satz", "turkish": "Pencereyi kapatayım mı?", "example": "Ist es Ihnen zu kalt?" },
    { "id": 120, "category": "Dialoge", "german": "Was kann ich für Sie tun?", "type": "Satz", "turkish": "Sizin için ne yapabilirim?", "example": "Brauchen Sie noch etwas?" },
    { "id": 121, "category": "Dialoge", "german": "Haben Sie Stuhlgang gehabt?", "type": "Satz", "turkish": "Tuvalete çıktınız mı?", "example": "Haben Sie heute schon Stuhlgang gehabt?" },
    { "id": 122, "category": "Dialoge", "german": "Darf ich Fieber messen?", "type": "Satz", "turkish": "Ateşinizi ölçebilir miyim?", "example": "Darf ich bei Ihnen Fieber messen?" },
    { "id": 123, "category": "Dialoge", "german": "Bitte machen Sie den Arm frei.", "type": "Satz", "turkish": "Lütfen kolunuzu açın.", "example": "Bitte machen Sie den Arm frei für die Blutabnahme." },
    { "id": 124, "category": "Dialoge", "german": "Wann haben Sie das letzte Mal gegessen?", "type": "Satz", "turkish": "En son ne zaman yemek yediniz?", "example": "Wann haben Sie vor der OP das letzte Mal gegessen?" },
    { "id": 125, "category": "Dialoge", "german": "Atmen Sie ganz normal weiter.", "type": "Satz", "turkish": "Normal nefes almaya devam edin.", "example": "Entspannen Sie sich und atmen Sie ganz normal weiter." },
    { "id": 126, "category": "Dialoge", "german": "Haben Sie heute schon Wasser gelassen?", "type": "Satz", "turkish": "İdrara çıktınız mı?", "example": "Haben Sie heute schon Wasser gelassen?" },
    { "id": 127, "category": "Dialoge", "german": "Ich wechsle jetzt Ihren Verband.", "type": "Satz", "turkish": "Şimdi pansumanınızı değiştireceğim.", "example": "Es tut nicht weh, ich wechsle jetzt Ihren Verband." },
    { "id": 128, "category": "Dialoge", "german": "Haben Sie Begleitpersonen dabei?", "type": "Satz", "turkish": "Yanınızda refakatçi var mı?", "example": "Haben Sie Angehörige veya Begleitpersonen dabei?" },
    { "id": 129, "category": "Dialoge", "german": "Wo genau tut es weh?", "type": "Satz", "turkish": "Tam olarak neresi ağrıyor?", "example": "Zeigen Sie mir: Wo genau tut es weh?" },
    { "id": 130, "category": "Dialoge", "german": "Bitte drehen Sie sich auf die Seite.", "type": "Satz", "turkish": "Lütfen yan dönün.", "example": "Bitte drehen Sie sich auf die Seite für die Spritze." },
    { "id": 131, "category": "Dialoge", "german": "Wir fahren Sie jetzt in den OP.", "type": "Satz", "turkish": "Sizi şimdi ameliyathaneye götürüyoruz.", "example": "Alles ist bereit, wir fahren Sie jetzt in den OP." },
    { "id": 132, "category": "Dialoge", "german": "Ist Ihnen schwindelig?", "type": "Satz", "turkish": "Başınız dönüyor mu?", "example": "Setzen Sie sich bitte, ist Ihnen schwindelig?" },
    { "id": 133, "category": "Dialoge", "german": "Bitte bleiben Sie nüchtern.", "type": "Satz", "turkish": "Lütfen aç kalın.", "example": "Bitte bleiben Sie ab Mitternacht nüchtern." },
    { "id": 134, "category": "Dialoge", "german": "Ziehen Sie bitte den Oberkörper aus.", "type": "Satz", "turkish": "Lütfen üstünüzü soyunun.", "example": "Ziehen Sie bitte den Oberkörper aus für das EKG." },
    { "id": 135, "category": "Dialoge", "german": "Das Bett ist frisch bezogen.", "type": "Satz", "turkish": "Yatak yeni yapıldı.", "example": "Legen Sie sich gerne hin, das Bett ist frisch bezogen." },
    { "id": 136, "category": "Dialoge", "german": "Haben Sie eine Patientenverfügung?", "type": "Satz", "turkish": "Hasta vasiyetnameniz var mı?", "example": "Für die Unterlagen: Haben Sie eine Patientenverfügung?" },
    { "id": 137, "category": "Dialoge", "german": "Brauchen Sie ein Schmerzmittel?", "type": "Satz", "turkish": "Ağrı kesiciye ihtiyacınız var mı?", "example": "Wenn die Schmerzen stark sind, brauchen Sie ein Schmerzmittel?" },
    { "id": 138, "category": "Dialoge", "german": "Wir müssen Sie wiegen.", "type": "Satz", "turkish": "Sizi tartmamız gerekiyor.", "example": "Kommen Sie bitte mit, wir müssen Sie wiegen." },
    { "id": 139, "category": "Dialoge", "german": "Die Infusion ist fertig.", "type": "Satz", "turkish": "Serum bitti.", "example": "Ich sehe, die Infusion ist fertig. Ich werde sie jetzt entfernen." },
    { "id": 140, "category": "Dialoge", "german": "Öffnen Sie den Mund ganz weit.", "type": "Satz", "turkish": "Ağzınızı kocaman açın.", "example": "Sagen Sie 'Aaa', öffnen Sie den Mund ganz weit." },
    { "id": 141, "category": "Dialoge", "german": "Nehmen Sie die Tabletten nach dem Essen ein.", "type": "Satz", "turkish": "Hapları yemekten sonra alın.", "example": "Sehr wichtig: Nehmen Sie die Tabletten nach dem Essen ein." },
    { "id": 142, "category": "Dialoge", "german": "Ich helfe Ihnen beim Waschen.", "type": "Satz", "turkish": "Yıkanmanıza yardım edeceğim.", "example": "Guten Morgen, ich helfe Ihnen beim Waschen." },
    { "id": 143, "category": "Dialoge", "german": "Haben Sie Schluckbeschwerden?", "type": "Satz", "turkish": "Yutkunma zorluğu çekiyor musunuz?", "example": "Haben Sie beim Essen Schluckbeschwerden?" },
    { "id": 144, "category": "Dialoge", "german": "Können Sie Ihre Beine bewegen?", "type": "Satz", "turkish": "Bacaklarınızı hareket ettirebiliyor musunuz?", "example": "Sagen Sie mir: Können Sie Ihre Beine bewegen?" },
    { "id": 145, "category": "Dialoge", "german": "Das ist nur ein kleiner Piks.", "type": "Satz", "turkish": "Bu sadece minicik bir iğne acısı, sinek ısırığı gibi.", "example": "Haben Sie keine Angst, das ist nur ein kleiner Piks." },
    { "id": 146, "category": "Dialoge", "german": "Ihre Werte sind stabil.", "type": "Satz", "turkish": "Değerleriniz normal.", "example": "Gute Nachrichten, Ihre Werte sind stabil." },
    { "id": 147, "category": "Dialoge", "german": "Sie können heute aufstehen.", "type": "Satz", "turkish": "Bugün ayağa kalkabilirsiniz.", "example": "Der Arzt sagt: Sie können heute aufstehen." },
    { "id": 148, "category": "Dialoge", "german": "Die Besuchszeiten sind von 14:00 bis 20:00 Uhr.", "type": "Satz", "turkish": "Ziyaret saatleri 14:00 ile 20:00 arasındadır.", "example": "Sagen Sie Ihren Verwandten: Die Besuchszeiten sind von 14:00 bis 20:00 Uhr." },
    { "id": 149, "category": "Dialoge", "german": "Ich hole die Bettpfanne.", "type": "Satz", "turkish": "Sürgüyü getiriyorum.", "example": "Einen Moment, ich hole die Bettpfanne." },
    { "id": 150, "category": "Dialoge", "german": "Wir machen jetzt Übergabe.", "type": "Satz", "turkish": "Şimdi nöbet teslimi yapıyoruz.", "example": "Die Schicht ist zu Ende, wir machen jetzt Übergabe." },

    // --- NEUE HEMŞİRELİK KELİMELERİ (151-165) ---
    { "id": 151, "category": "Allgemein", "german": "Fachabteilung", "type": "Die Nomen", "turkish": "Uzmanlık alanı / Bölüm", "example": "In welche Fachabteilung wird der Patient verlegt?" },
    { "id": 152, "category": "Ausrüstung", "german": "Braunüle", "type": "Die Nomen", "turkish": "Branül / Damar yolu kanülü", "example": "Ich muss eine neue Braunüle legen." },
    
    { "id": 153, "category": "Aktion", "german": "Umlagern", "type": "Das Verb", "turkish": "Pozisyonunu değiştirmek (Yatak içi)", "example": "Wir müssen den Patienten alle zwei Stunden umlagern." },
    { "id": 154, "category": "Symptome", "german": "Juckreiz", "type": "Der Nomen", "turkish": "Kaşıntı", "example": "Hat der Patient Juckreiz nach der Infusion?" },
    { "id": 155, "category": "Ausrüstung", "german": "Infusionspumpe / Perfusor", "type": "Die Nomen", "turkish": "İnfüzyon pompası", "example": "Der Perfusor gibt Alarm." },
    
    { "id": 156, "category": "Aktion", "german": "Überwachen", "type": "Das Verb", "turkish": "Gözlemlemek / Monitorize etmek", "example": "Wir müssen die Vitalwerte kontinuierlich überwachen." },
    { "id": 157, "category": "Medikamente", "german": "Bedarfsmedikation", "type": "Die Nomen", "turkish": "Gerektiğinde kullanılan ilaç", "example": "Hat der Patient eine Bedarfsmedikation gegen Schmerzen?" },
    { "id": 158, "category": "Notfall", "german": "Stabil", "type": "Adjektiv", "turkish": "Stabil / Durumu sabit", "example": "Der Zustand des Patienten ist jetzt stabil." },
    { "id": 159, "category": "Personal", "german": "Nachtschicht", "type": "Die Nomen", "turkish": "Gece vardiyası", "example": "Wer hat heute Nachtschicht?" },
    { "id": 160, "category": "Ausrüstung", "german": "Patientenklingel", "type": "Die Nomen", "turkish": "Hasta çağrı zili", "example": "Der Patient drückt ständig die Klingel." },
    { "id": 161, "category": "Allgemein", "german": "Befund", "type": "Der Nomen", "turkish": "Bulgu / Sonuç", "example": "Der Laborbefund ist noch nicht da." },
    { "id": 162, "category": "Aktion", "german": "Dokumentieren", "type": "Das Verb", "turkish": "Kaydetmek / Dokümantasyon", "example": "Bitte dokumentieren Sie den Vorfall im System." },
    { "id": 163, "category": "Symptome", "german": "Taubheitsgefühl", "type": "Das Nomen", "turkish": "Uyuşma hissi", "example": "Haben Sie ein Taubheitsgefühl in den Fingern?" },
    { "id": 164, "category": "Ausrüstung", "german": "Magensonde", "type": "Die Nomen", "turkish": "Mide sondası", "example": "Die Magensonde muss überprüft werden." },
    { "id": 165, "category": "Medikamente", "german": "Nüchtern", "type": "Adjektiv", "turkish": "Aç karnına", "example": "Der Patient muss für die OP nüchtern bleiben." },

    // --- NEUE DIALOGE (166-185) ---
    { "id": 166, "category": "Dialoge", "german": "Auf einer Skala von 1 bis 10, wie stark sind Ihre Schmerzen?", "type": "Satz", "turkish": "1'den 10'a kadar bir skalada ağrınız ne kadar güçlü?", "example": "Sagen Sie mir bitte: Auf einer Skala von 1 bis 10, wie stark sind Ihre Schmerzen?" },
    
    { "id": 167, "category": "Dialoge", "german": "Haben Sie heute schon Wasser gelassen?", "type": "Satz", "turkish": "Bugün idrarınızı yaptınız mı?", "example": "Das ist wichtig für die Kontrolle: Haben Sie heute schon Wasser gelassen?" },
    { "id": 168, "category": "Dialoge", "german": "Ich muss Ihnen Blut abnehmen.", "type": "Satz", "turkish": "Sizden kan almam gerekiyor.", "example": "Setzen Sie sich bitte hin, ich muss Ihnen Blut abnehmen." },
    { "id": 169, "category": "Dialoge", "german": "Darf ich Ihren Verband kontrollieren?", "type": "Satz", "turkish": "Pansumanınızı kontrol edebilir miyim?", "example": "Guten Morgen, darf ich kurz Ihren Verband kontrollieren?" },
    { "id": 170, "category": "Dialoge", "german": "Sind Sie gegen irgendwelche Medikamente allergisch?", "type": "Satz", "turkish": "Herhangi bir ilaca karşı alerjiniz var mı?", "example": "Bevor wir anfangen: Sind Sie gegen irgendwelche Medikamente allergisch?" },
    { "id": 171, "category": "Dialoge", "german": "Bitte bleiben Sie im Bett liegen.", "type": "Satz", "turkish": "Lütfen yatakta kalın.", "example": "Es ist zu gefährlich, bitte bleiben Sie im Bett liegen." },
    { "id": 172, "category": "Dialoge", "german": "Brauchen Sie Hilfe beim Gang zur Toilette?", "type": "Satz", "turkish": "Tuvalete giderken yardıma ihtiyacınız var mı?", "example": "Klingeln Sie bitte, wenn Sie Hilfe beim Gang zur Toilette brauchen." },
    { "id": 173, "category": "Dialoge", "german": "Der Arzt wird Sie gleich untersuchen.", "type": "Satz", "turkish": "Doktor sizi birazdan muayene edecek.", "example": "Haben Sie ein wenig Geduld, der Arzt wird Sie gleich untersuchen." },
    { "id": 174, "category": "Dialoge", "german": "Ich stelle Ihnen jetzt den Perfusor ein.", "type": "Satz", "turkish": "Şimdi infüzyon pompasını (perfusor) ayarlıyorum.", "example": "Einen Moment bitte, ich stelle Ihnen jetzt den Perfusor ein." },
    { "id": 175, "category": "Dialoge", "german": "Wie war Ihre Nacht?", "type": "Satz", "turkish": "Geceniz nasıl geçti?", "example": "Guten Morgen Herr Müller, wie war Ihre Nacht?" },
    { "id": 176, "category": "Dialoge", "german": "Ich muss Ihren Blutzucker messen.", "type": "Satz", "turkish": "Kan şekerinizi ölçmem gerekiyor.", "example": "Geben Sie mir bitte Ihren Finger, ich muss Ihren Blutzucker messen." },
    { "id": 177, "category": "Dialoge", "german": "Bitte atmen Sie tief ein und aus.", "type": "Satz", "turkish": "Lütfen derin nefes alın ve verin.", "example": "Beim Abhören der Lunge: Bitte atmen Sie tief ein und aus." },
    { "id": 178, "category": "Dialoge", "german": "Ist der Schmerz stechend oder ziehend?", "type": "Satz", "turkish": "Ağrı saplanır gibi mi yoksa çekilir gibi mi?", "example": "Beschreiben Sie den Schmerz: Ist er stechend oder ziehend?" },
    { "id": 179, "category": "Dialoge", "german": "Machen Sie sich keine Sorgen, alles wird gut.", "type": "Satz", "turkish": "Endişelenmeyin, her şey iyi olacak.", "example": "Wir sind bei Ihnen, machen Sie sich keine Sorgen." },
    { "id": 180, "category": "Dialoge", "german": "Haben Sie heute schon gefrühstückt?", "type": "Satz", "turkish": "Bugün kahvaltı yaptınız mı?", "example": "Vor der Medikamentengabe: Haben Sie heute schon gefrühstückt?" },
    { "id": 181, "category": "Dialoge", "german": "Ich muss jetzt die Wunde reinigen.", "type": "Satz", "turkish": "Şimdi yarayı temizlemem gerekiyor.", "example": "Halten Sie still, ich muss jetzt die Wunde reinigen." },
    { "id": 182, "category": "Dialoge", "german": "Wann treten die Schmerzen meistens auf?", "type": "Satz", "turkish": "Ağrılar çoğunlukla ne zaman ortaya çıkıyor?", "example": "Morgens oder abends? Wann treten die Schmerzen auf?" },
    { "id": 183, "category": "Dialoge", "german": "Haben Sie Schwierigkeiten beim Atmen?", "type": "Satz", "turkish": "Nefes alırken zorluk çekiyor musunuz?", "example": "Sagen Sie mir: Haben Sie Schwierigkeiten beim Atmen?" },
    { "id": 184, "category": "Dialoge", "german": "Ich werde jetzt Ihre Vitalwerte kontrollieren.", "type": "Satz", "turkish": "Şimdi yaşam bulgularınızı (tansiyon, nabız vs.) kontrol edeceğim.", "example": "Einen Moment Geduld, ich werde Ihre Vitalwerte kontrollieren." },
    { "id": 185, "category": "Dialoge", "german": "Haben Sie jemanden, der Sie heute abholt?", "type": "Satz", "turkish": "Bugün sizi alacak birisi var mı?", "example": "Bei der Entlassung: Haben Sie jemanden, der Sie abholt?" }
];
