const vocabularyData = [
    // --- ALLGEMEIN ---
    { "id": 1, "category": "Allgemein", "german": "Krankenhaus", "type": "Das Nomen", "turkish": "Hastane", "english": "Hospital", "example": "Das Krankenhaus ist in der Nähe." },
    { "id": 2, "category": "Allgemein", "german": "Notaufnahme", "type": "Die Nomen", "turkish": "Acil Servis", "english": "Emergency Room (ER)", "example": "Bringen Sie ihn sofort in die Notaufnahme!" },
    { "id": 3, "category": "Allgemein", "german": "Station", "type": "Die Nomen", "turkish": "Servis / Bölüm", "english": "Ward", "example": "Er liegt auf der kardiologischen Station." },
    { "id": 4, "category": "Allgemein", "german": "Patient", "type": "Der Nomen", "turkish": "Hasta", "english": "Patient", "example": "Der Patient schläft noch." },
    { "id": 5, "category": "Allgemein", "german": "Arzt", "type": "Der Nomen", "turkish": "Doktor", "english": "Doctor / Physician", "example": "Der Arzt kommt gleich zur Visite." },
    { "id": 6, "category": "Allgemein", "german": "Visite", "type": "Die Nomen", "turkish": "Doktor Viziti", "english": "Ward Round", "example": "Die Visite beginnt um 8 Uhr." },
    { "id": 7, "category": "Allgemein", "german": "Diagnose", "type": "Die Nomen", "turkish": "Teşhis", "english": "Diagnosis", "example": "Die Diagnose ist noch nicht sicher." },
    { "id": 8, "category": "Allgemein", "german": "Rezept", "type": "Das Nomen", "turkish": "Reçete", "english": "Prescription", "example": "Ich schreibe Ihnen ein Rezept auf." },
    { "id": 9, "category": "Allgemein", "german": "Behandlung", "type": "Die Nomen", "turkish": "Tedavi", "english": "Treatment", "example": "Die Behandlung dauert zwei Wochen." },
    { "id": 10, "category": "Allgemein", "german": "Untersuchung", "type": "Die Nomen", "turkish": "Muayene", "english": "Examination", "example": "Die Untersuchung war schmerzlos." },
    { "id": 11, "category": "Allgemein", "german": "Überweisung", "type": "Die Nomen", "turkish": "Sevk", "english": "Referral", "example": "Sie brauchen eine Überweisung." },
    { "id": 12, "category": "Allgemein", "german": "Entlassung", "type": "Die Nomen", "turkish": "Taburcu olma", "english": "Discharge", "example": "Die Entlassung ist für morgen geplant." },
    { "id": 13, "category": "Allgemein", "german": "Aufnahme", "type": "Die Nomen", "turkish": "Kayıt / Kabul", "english": "Admission", "example": "Bitte gehen Sie zuerst zur Aufnahme." },
    { "id": 14, "category": "Allgemein", "german": "Labor", "type": "Das Nomen", "turkish": "Laboratuvar", "english": "Laboratory", "example": "Die Proben sind bereits im Labor." },
    { "id": 15, "category": "Allgemein", "german": "Krankenkasse", "type": "Die Nomen", "turkish": "Sağlık Sigortası", "english": "Health Insurance", "example": "Haben Sie Ihre Krankenkassenkarte dabei?" },
    
    // --- ANATOMIE ---
    { "id": 16, "category": "Anatomie", "german": "Herz", "type": "Das Nomen", "turkish": "Kalp", "english": "Heart", "example": "Das Herz schlägt schnell." },
    { "id": 17, "category": "Anatomie", "german": "Lunge", "type": "Die Nomen", "turkish": "Akciğer", "english": "Lungs", "example": "Atmen Sie tief in die Lunge ein." },
    { "id": 18, "category": "Anatomie", "german": "Gehirn", "type": "Das Nomen", "turkish": "Beyin", "english": "Brain", "example": "Das Gehirn ist sehr komplex." },
    { "id": 19, "category": "Anatomie", "german": "Magen", "type": "Der Nomen", "turkish": "Mide", "english": "Stomach", "example": "Ich habe Schmerzen im Magen." },
    { "id": 20, "category": "Anatomie", "german": "Leber", "type": "Die Nomen", "turkish": "Karaciğer", "english": "Liver", "example": "Alkohol schadet der Leber." },
    { "id": 21, "category": "Anatomie", "german": "Niere", "type": "Die Nomen", "turkish": "Böbrek", "english": "Kidney", "example": "Der Patient has Nierenschmerzen." },
    { "id": 22, "category": "Anatomie", "german": "Blut", "type": "Das Nomen", "turkish": "Kan", "english": "Blood", "example": "Wir brauchen eine Blutprobe." },
    { "id": 23, "category": "Anatomie", "german": "Knochen", "type": "Der Nomen", "turkish": "Kemik", "english": "Bone", "example": "Der Knochen ist gebrochen." },
    { "id": 24, "category": "Anatomie", "german": "Haut", "type": "Die Nomen", "turkish": "Cilt", "english": "Skin", "example": "Die Haut ist gerötet." },
    { "id": 25, "category": "Anatomie", "german": "Ader", "type": "Die Nomen", "turkish": "Damar / Ven", "english": "Vein / Blood vessel", "example": "Ich finde keine gute Ader." },
    { "id": 26, "category": "Anatomie", "german": "Wirbelsäule", "type": "Die Nomen", "turkish": "Omurga", "english": "Spine", "example": "Er hat Probleme mit der Wirbelsäule." },
    { "id": 27, "category": "Anatomie", "german": "Gelenk", "type": "Das Nomen", "turkish": "Eklem", "english": "Joint", "example": "Das Kniegelenk ist geschwollen." },
    { "id": 28, "category": "Anatomie", "german": "Muskel", "type": "Der Nomen", "turkish": "Kas", "english": "Muscle", "example": "Ich habe einen Muskelkater." },
    { "id": 29, "category": "Anatomie", "german": "Nerv", "type": "Der Nomen", "turkish": "Sinir", "english": "Nerve", "example": "Ein Nerv ist eingeklemmt." },
    { "id": 30, "category": "Anatomie", "german": "Bauch", "type": "Der Nomen", "turkish": "Karın", "english": "Abdomen", "example": "Der Bauch ist weich." },

    // --- AKTION ---
    { "id": 31, "category": "Aktion", "german": "Messen", "type": "Das Verb", "turkish": "Ölçmek", "english": "To measure", "example": "Ich messe jetzt das Fieber." },
    { "id": 32, "category": "Aktion", "german": "Spritzen", "type": "Das Verb", "turkish": "İğne yapmak", "english": "To inject", "example": "Soll ich das Insulin spritzen?" },
    { "id": 33, "category": "Aktion", "german": "Verbinden", "type": "Das Verb", "turkish": "Sarmak / Pansuman", "english": "To bandage / dress", "example": "Ich muss die Wunde neu verbinden." },
    { "id": 34, "category": "Aktion", "german": "Waschen", "type": "Das Verb", "turkish": "Yıkamak", "english": "To wash", "example": "Soll ich Ihnen beim Waschen helfen?" },
    { "id": 35, "category": "Aktion", "german": "Füttern", "type": "Das Verb", "turkish": "Beslemek", "english": "To feed", "example": "Ich muss den Patienten füttern." },
    { "id": 36, "category": "Aktion", "german": "Lagern", "type": "Das Verb", "turkish": "Pozisyon vermek", "english": "To position", "example": "Wir müssen den Patienten lagern." },
    { "id": 37, "category": "Aktion", "german": "Mobilisieren", "type": "Das Verb", "turkish": "Hareket ettirmek", "english": "To mobilize", "example": "Wir wollen den Patienten heute mobilisieren." },
    { "id": 38, "category": "Aktion", "german": "Dokumentieren", "type": "Das Verb", "turkish": "Kaydetmek", "english": "To document", "example": "Ich muss die Werte dokumentieren." },
    { "id": 39, "category": "Aktion", "german": "Desinfizieren", "type": "Das Verb", "turkish": "Dezenfekte etmek", "english": "To disinfect", "example": "Bitte die Hände desinfizieren." },
    { "id": 40, "category": "Aktion", "german": "Absaugen", "type": "Das Verb", "turkish": "Aspire etmek", "english": "To suction", "example": "Ich muss den Schleim absaugen." },

    // --- SYMPTOME ---
    { "id": 41, "category": "Symptome", "german": "Schmerz", "type": "Der Nomen", "turkish": "Ağrı", "english": "Pain", "example": "Wo genau haben Sie Schmerzen?" },
    { "id": 42, "category": "Symptome", "german": "Fieber", "type": "Das Nomen", "turkish": "Ateş", "english": "Fever", "example": "Das Fieber sinkt langsam." },
    { "id": 43, "category": "Symptome", "german": "Husten", "type": "Der Nomen", "turkish": "Öksürük", "english": "Cough", "example": "Haben Sie trockenen Husten?" },
    { "id": 44, "category": "Symptome", "german": "Übelkeit", "type": "Die Nomen", "turkish": "Bulantı", "english": "Nausea", "example": "Ist Ihnen übel?" },
    { "id": 45, "category": "Symptome", "german": "Schwindel", "type": "Der Nomen", "turkish": "Baş dönmesi", "english": "Dizziness", "example": "Ich habe Schwindelgefühle." },
    { "id": 46, "category": "Symptome", "german": "Atemnot", "type": "Die Nomen", "turkish": "Nefes darlığı", "english": "Shortness of breath", "example": "Haben Sie Atemnot beim Gehen?" },
    { "id": 47, "category": "Symptome", "german": "Erbrechen", "type": "Das Nomen", "turkish": "Kusma", "english": "Vomiting", "example": "Der Patient leidet unter Erbrechen." },
    { "id": 48, "category": "Symptome", "german": "Durchfall", "type": "Der Nomen", "turkish": "İshal", "english": "Diarrhea", "example": "Seit wann haben Sie Durchfall?" },
    { "id": 49, "category": "Symptome", "german": "Verstopfung", "type": "Die Nomen", "turkish": "Kabızlık", "english": "Constipation", "example": "Leiden Sie unter Verstopfung?" },
    { "id": 50, "category": "Symptome", "german": "Blutung", "type": "Die Nomen", "turkish": "Kanama", "english": "Bleeding", "example": "Die Blutung hat aufgehört." },

    // --- AUSRÜSTUNG ---
    { "id": 51, "category": "Ausrüstung", "german": "Blutdruckmessgerät", "type": "Das Nomen", "turkish": "Tansiyon aleti", "english": "Blood pressure monitor", "example": "Das Blutdruckmessgerät ist kaputt." },
    { "id": 52, "category": "Ausrüstung", "german": "Stethoskop", "type": "Das Nomen", "turkish": "Stetoskop", "english": "Stethoscope", "example": "Ich brauche ein Stethoskop." },
    { "id": 53, "category": "Ausrüstung", "german": "Spritze", "type": "Die Nomen", "turkish": "Şırınga", "english": "Syringe", "example": "Geben Sie mir eine 5ml Spritze." },
    { "id": 54, "category": "Ausrüstung", "german": "Rollstuhl", "type": "Der Nomen", "turkish": "Tekerlekli sandalye", "english": "Wheelchair", "example": "Bitte bringen Sie einen Rollstuhl." },
    { "id": 55, "category": "Ausrüstung", "german": "Gehstützen", "type": "Die Nomen", "turkish": "Koltuk değneği", "english": "Crutches", "example": "Er braucht Gehstützen." },
    { "id": 56, "category": "Ausrüstung", "german": "Infusionsständer", "type": "Der Nomen", "turkish": "Serum askısı", "english": "IV pole", "example": "Der Infusionsständer wackelt." },
    { "id": 57, "category": "Ausrüstung", "german": "Thermometer", "type": "Das Nomen", "turkish": "Ateşölçer", "english": "Thermometer", "example": "Haben Sie ein Thermometer?" },
    { "id": 58, "category": "Ausrüstung", "german": "Verband", "type": "Der Nomen", "turkish": "Sargı", "english": "Bandage", "example": "Der Verband ist nass." },
    { "id": 59, "category": "Ausrüstung", "german": "Handschuhe", "type": "Die Nomen", "turkish": "Eldiven", "english": "Gloves", "example": "Ich trage Einmalhandschuhe." },
    { "id": 60, "category": "Ausrüstung", "german": "Pflaster", "type": "Das Nomen", "turkish": "Yara bandı", "english": "Band-aid / Plaster", "example": "Ein kleines Pflaster reicht." },
    { "id": 61, "category": "Ausrüstung", "german": "Bettpfanne", "type": "Die Nomen", "turkish": "Sürgü / Ördek", "english": "Bedpan", "example": "Der Patient braucht die Bettpfanne." },
    { "id": 62, "category": "Ausrüstung", "german": "Katheter", "type": "Der Nomen", "turkish": "Kateter", "english": "Catheter", "example": "Der Katheter muss geleert werden." },
    { "id": 63, "category": "Ausrüstung", "german": "EKG-Gerät", "type": "Das Nomen", "turkish": "EKG cihazı", "english": "ECG machine", "example": "Schließen Sie das EKG-Gerät an." },
    { "id": 64, "category": "Ausrüstung", "german": "Sauerstoffmaske", "type": "Die Nomen", "turkish": "Oksijen Maskesi", "english": "Oxygen mask", "example": "Wir legen die Sauerstoffmaske an." },
    { "id": 65, "category": "Ausrüstung", "german": "Defibrillator", "type": "Der Nomen", "turkish": "Defibrilatör", "english": "Defibrillator", "example": "Bringt den Defibrillator mit!" },

    // --- PERSONAL ---
    { "id": 66, "category": "Personal", "german": "Pflegefachkraft", "type": "Die Nomen", "turkish": "Hemşire", "english": "Nurse / Nursing professional", "example": "Ich bin heute Ihre Pflegefachkraft." },
    { "id": 67, "category": "Personal", "german": "Oberarzt", "type": "Der Nomen", "turkish": "Uzman doktor", "english": "Senior physician / Attending", "example": "Der Oberarzt macht heute Dienst." },
    { "id": 68, "category": "Personal", "german": "Chefarzt", "type": "Der Nomen", "turkish": "Başhekim", "english": "Chief physician", "example": "Der Chefarzt ist im Operationssaal." },
    { "id": 69, "category": "Personal", "german": "Stationsleitung", "type": "Die Nomen", "turkish": "Servis sorumlusu", "english": "Ward manager", "example": "Sprechen Sie mit der Stationsleitung." },
    { "id": 70, "category": "Personal", "german": "Physiotherapeut", "type": "Der Nomen", "turkish": "Fizyoterapist", "english": "Physiotherapist", "example": "Der Physiotherapeut kommt um 10 Uhr." },
    { "id": 71, "category": "Personal", "german": "Logopäde", "type": "Der Nomen", "turkish": "Konuşma terapisti", "english": "Speech therapist", "example": "Der Logopäde hilft beim Schlucken." },
    { "id": 72, "category": "Personal", "german": "Hebamme", "type": "Die Nomen", "turkish": "Ebe", "english": "Midwife", "example": "Die Hebamme ist im Kreißsaal." },
    { "id": 73, "category": "Personal", "german": "Auszubildende", "type": "Die Nomen", "turkish": "Stajyer", "english": "Trainee / Student nurse", "example": "Unsere Auszubildende hilft Ihnen." },
    { "id": 74, "category": "Personal", "german": "Reinigungskraft", "type": "Die Nomen", "turkish": "Temizlik görevlisi", "english": "Cleaner / Janitor", "example": "Die Reinigungskraft kommt in Kürze." },
    { "id": 75, "category": "Personal", "german": "Rettungssanitäter", "type": "Der Nomen", "turkish": "Paramedik", "english": "Paramedic", "example": "Die Rettungssanitäter sind da." },

    // --- MEDIKAMENTE ---
    { "id": 76, "category": "Medikamente", "german": "Schmerzmittel", "type": "Das Nomen", "turkish": "Ağrı kesici", "english": "Painkiller", "example": "Brauchen Sie noch ein Schmerzmittel?" },
    { "id": 77, "category": "Medikamente", "german": "Antibiotikum", "type": "Das Nomen", "turkish": "Antibiyotik", "english": "Antibiotic", "example": "Sie müssen das Antibiotikum zu Ende nehmen." },
    { "id": 78, "category": "Medikamente", "german": "Schlaftablette", "type": "Die Nomen", "turkish": "Uyku ilacı", "english": "Sleeping pill", "example": "Hier ist Ihre Schlaftablette." },
    { "id": 79, "category": "Medikamente", "german": "Salbe", "type": "Die Nomen", "turkish": "Merhem", "english": "Ointment", "example": "Tragen Sie diese Salbe zweimal täglich auf." },
    { "id": 80, "category": "Medikamente", "german": "Tropfen", "type": "Die Nomen", "turkish": "Damla", "english": "Drops", "example": "Nehmen Sie 20 Tropfen vor dem Essen." },
    { "id": 81, "category": "Medikamente", "german": "Zäpfchen", "type": "Das Nomen", "turkish": "Fitil", "english": "Suppository", "example": "Das Zäpfchen ist gegen das Fieber." },
    { "id": 82, "category": "Medikamente", "german": "Infusion", "type": "Die Nomen", "turkish": "Serum", "english": "IV / Infusion", "example": "Die Infusion läuft noch." },
    { "id": 83, "category": "Medikamente", "german": "Nebenwirkung", "type": "Die Nomen", "turkish": "Yan etki", "english": "Side effect", "example": "Haben Sie Nebenwirkungen bemerkt?" },
    { "id": 84, "category": "Medikamente", "german": "Dosierung", "type": "Die Nomen", "turkish": "Doz", "english": "Dosage", "example": "Die Dosierung wurde geändert." },
    { "id": 85, "category": "Medikamente", "german": "Beruhigungsmittel", "type": "Das Nomen", "turkish": "Sakinleştirici", "english": "Sedative", "example": "Er hat ein Beruhigungsmittel genommen." },

    // --- NOTFALL ---
    { "id": 86, "category": "Notfall", "german": "Bewusstlos", "type": "Adjektiv", "turkish": "Bilinci kapalı", "english": "Unconscious", "example": "Der Patient ist bewusstlos." },
    { "id": 87, "category": "Notfall", "german": "Wiederbelebung", "type": "Die Nomen", "turkish": "Kalp masajı / CPR", "english": "CPR / Resuscitation", "example": "Wir beginnen mit der Wiederbelebung." },
    { "id": 88, "category": "Notfall", "german": "Koma", "type": "Das Nomen", "turkish": "Koma", "english": "Coma", "example": "Er liegt im künstlichen Koma." },
    { "id": 89, "category": "Notfall", "german": "Erste Hilfe", "type": "Die Nomen", "turkish": "İlk Yardım", "english": "First Aid", "example": "Erste Hilfe ist hier sehr wichtig." },
    { "id": 90, "category": "Notfall", "german": "Herzstillstand", "type": "Der Nomen", "turkish": "Kalp durması", "english": "Cardiac arrest", "example": "Er hatte einen Herzstillstand." },
    { "id": 91, "category": "Notfall", "german": "Schock", "type": "Der Nomen", "turkish": "Şok", "english": "Shock", "example": "Der Patient steht unter Schock." },
    { "id": 92, "category": "Notfall", "german": "Verletzung", "type": "Die Nomen", "turkish": "Yaralanma", "english": "Injury", "example": "Die Verletzung ist schwer." },
    { "id": 93, "category": "Notfall", "german": "Wunde", "type": "Die Nomen", "turkish": "Yara", "english": "Wound", "example": "Die Wunde blutet stark." },
    { "id": 94, "category": "Notfall", "german": "Verbrennung", "type": "Die Nomen", "turkish": "Yanık", "english": "Burn", "example": "Er hat eine Verbrennung dritten Grades." },
    { "id": 95, "category": "Notfall", "german": "Notarzt", "type": "Der Nomen", "turkish": "Acil Doktoru", "english": "Emergency doctor", "example": "Rufen Sie sofort den Notarzt!" },

    // --- KRANKHEITEN ---
    { "id": 96, "category": "Krankheiten", "german": "Krebs", "type": "Der Nomen", "turkish": "Kanser", "english": "Cancer", "example": "Er wird wegen Krebs behandelt." },
    { "id": 97, "category": "Krankheiten", "german": "Diabetes", "type": "Die Nomen", "turkish": "Şeker Hastalığı", "english": "Diabetes", "example": "Sie hat Diabetes Typ 2." },
    { "id": 98, "category": "Krankheiten", "german": "Asthma", "type": "Das Nomen", "turkish": "Astım", "english": "Asthma", "example": "Er benutzt sein Asthma-Spray." },
    { "id": 99, "category": "Krankheiten", "german": "Bluthochdruck", "type": "Der Nomen", "turkish": "Yüksek Tansiyon", "english": "High blood pressure", "example": "Bluthochdruck ist gefährlich." },
    { "id": 100, "category": "Krankheiten", "german": "Schlaganfall", "type": "Der Nomen", "turkish": "İnme / Felç", "english": "Stroke", "example": "Verdacht auf Schlaganfall." },
    { "id": 101, "category": "Krankheiten", "german": "Herzinfarkt", "type": "Der Nomen", "turkish": "Kalp Krizi", "english": "Heart attack", "example": "Er hatte einen leichten Herzinfarkt." },
    { "id": 102, "category": "Krankheiten", "german": "Grippe", "type": "Die Nomen", "turkish": "Grip", "english": "Flu", "example": "Die Grippe ist dieses Jahr sehr stark." },
    { "id": 103, "category": "Krankheiten", "german": "Entzündung", "type": "Die Nomen", "turkish": "İltihap / Enfeksiyon", "english": "Inflammation / Infection", "example": "Das ist eine bakterielle Entzündung." },
    { "id": 104, "category": "Krankheiten", "german": "Allergie", "type": "Die Nomen", "turkish": "Alerji", "english": "Allergy", "example": "Haben Sie eine Allergie gegen Nüsse?" },
    { "id": 105, "category": "Krankheiten", "german": "Demenz", "type": "Die Nomen", "turkish": "Demans / Bunama", "english": "Dementia", "example": "Der Patient leidet an Demenz." },

    // --- DIALOGE ---
    { "id": 106, "category": "Dialoge", "german": "Wie geht es Ihnen?", "type": "Satz", "turkish": "Nasılsınız?", "english": "How are you?", "example": "Guten Morgen, wie geht es Ihnen?" },
    { "id": 107, "category": "Dialoge", "german": "Haben Sie Schmerzen?", "type": "Satz", "turkish": "Ağrınız var mı?", "english": "Do you have pain?", "example": "Sagen Sie mir, haben Sie Schmerzen?" },
    { "id": 108, "category": "Dialoge", "german": "Ich bringe Ihnen die Medikamente.", "type": "Satz", "turkish": "Size ilaçları getiriyorum.", "english": "I'm bringing your medication.", "example": "Hier sind Ihre Tabletten." },
    { "id": 109, "category": "Dialoge", "german": "Können Sie mich verstehen?", "type": "Satz", "turkish": "Beni anlayabiliyor musunuz?", "english": "Can you understand me?", "example": "Hallo, können Sie mich verstehen?" },
    { "id": 110, "category": "Dialoge", "german": "Drücken Sie die Klingel.", "type": "Satz", "turkish": "Zile basın.", "english": "Press the bell.", "example": "Wenn etwas passiert, klingeln Sie bitte." },
    { "id": 111, "category": "Dialoge", "german": "Haben Sie gut geschlafen?", "type": "Satz", "turkish": "İyi uyudunuz mu?", "english": "Did you sleep well?", "example": "Guten Tag, haben Sie gut geschlafen?" },
    { "id": 112, "category": "Dialoge", "german": "Ich helfe Ihnen beim Aufstehen.", "type": "Satz", "turkish": "Ayağa kalkmanıza yardım edeyim.", "english": "I'll help you get up.", "example": "Ich helfe Ihnen." },
    { "id": 113, "category": "Dialoge", "german": "Möchten Sie etwas trinken?", "type": "Satz", "turkish": "Bir şey içmek ister misiniz?", "english": "Would you like something to drink?", "example": "Hier ist Wasser, möchten Sie etwas trinken?" },
    { "id": 114, "category": "Dialoge", "german": "Ich werde jetzt Ihren Blutdruck messen.", "type": "Satz", "turkish": "Şimdi tansiyonunuzu ölçeceğim.", "english": "I will measure your blood pressure now.", "example": "Halten Sie Ihren Arm ruhig." },
    { "id": 115, "category": "Dialoge", "german": "Warten Sie einen Moment.", "type": "Satz", "turkish": "Bir dakika bekleyin.", "english": "Wait a moment.", "example": "Ich bin gleich wieder da." },
    { "id": 116, "category": "Dialoge", "german": "Der Arzt kommt gleich.", "type": "Satz", "turkish": "Doktor birazdan geliyor.", "english": "The doctor will come soon.", "example": "Bitte gedulden Sie sich einen Moment." },
    { "id": 117, "category": "Dialoge", "german": "Haben Sie Allergien?", "type": "Satz", "turkish": "Alerjiniz var mı?", "english": "Do you have allergies?", "example": "Haben Sie Allergien gegen Penicillin?" },
    { "id": 118, "category": "Dialoge", "german": "Gute Besserung!", "type": "Satz", "turkish": "Geçmiş olsun!", "english": "Get well soon!", "example": "Auf Wiedersehen und gute Besserung!" },
    { "id": 119, "category": "Dialoge", "german": "Soll ich das Fenster schließen?", "type": "Satz", "turkish": "Pencereyi kapatayım mı?", "english": "Should I close the window?", "example": "Ist es Ihnen zu kalt?" },
    { "id": 120, "category": "Dialoge", "german": "Was kann ich für Sie tun?", "type": "Satz", "turkish": "Sizin için ne yapabilirim?", "english": "What can I do for you?", "example": "Brauchen Sie noch etwas?" },
    { "id": 121, "category": "Dialoge", "german": "Haben Sie Stuhlgang gehabt?", "type": "Satz", "turkish": "Tuvalete çıktınız mı?", "english": "Have you had a bowel movement?", "example": "Haben Sie heute schon Stuhlgang gehabt?" },
    { "id": 122, "category": "Dialoge", "german": "Darf ich Fieber messen?", "type": "Satz", "turkish": "Ateşinizi ölçebilir miyim?", "english": "May I take your temperature?", "example": "Darf ich bei Ihnen Fieber messen?" },
    { "id": 123, "category": "Dialoge", "german": "Bitte machen Sie den Arm frei.", "type": "Satz", "turkish": "Lütfen kolunuzu açın.", "english": "Please bare your arm.", "example": "Bitte machen Sie den Arm frei für die Blutabnahme." },
    { "id": 124, "category": "Dialoge", "german": "Wann haben Sie das letzte Mal gegessen?", "type": "Satz", "turkish": "En son ne zaman yemek yediniz?", "english": "When was the last time you ate?", "example": "Wann haben Sie vor der OP das letzte Mal gegessen?" },
    { "id": 125, "category": "Dialoge", "german": "Atmen Sie ganz normal weiter.", "type": "Satz", "turkish": "Normal nefes almaya devam edin.", "english": "Keep breathing normally.", "example": "Entspannen Sie sich und atmen Sie ganz normal weiter." },
    { "id": 126, "category": "Dialoge", "german": "Haben Sie heute schon Wasser gelassen?", "type": "Satz", "turkish": "İdrara çıktınız mı?", "english": "Have you passed urine today?", "example": "Haben Sie heute schon Wasser gelassen?" },
    { "id": 127, "category": "Dialoge", "german": "Ich wechsle jetzt Ihren Verband.", "type": "Satz", "turkish": "Şimdi pansumanınızı değiştireceğim.", "english": "I am changing your bandage now.", "example": "Es tut nicht weh, ich wechsle jetzt Ihren Verband." },
    { "id": 128, "category": "Dialoge", "german": "Haben Sie Begleitpersonen dabei?", "type": "Satz", "turkish": "Yanınızda refakatçi var mı?", "english": "Do you have a companion with you?", "example": "Haben Sie Angehörige oder Begleitpersonen dabei?" },
    { "id": 129, "category": "Dialoge", "german": "Wo genau tut es weh?", "type": "Satz", "turkish": "Tam olarak neresi ağrıyor?", "english": "Where exactly does it hurt?", "example": "Zeigen Sie mir: Wo genau tut es weh?" },
    { "id": 130, "category": "Dialoge", "german": "Bitte drehen Sie sich auf die Seite.", "type": "Satz", "turkish": "Lütfen yan dönün.", "english": "Please turn on your side.", "example": "Bitte drehen Sie sich auf die Seite für die Spritze." },
    { "id": 131, "category": "Dialoge", "german": "Wir fahren Sie jetzt in den OP.", "type": "Satz", "turkish": "Sizi şimdi ameliyathaneye götürüyoruz.", "english": "We are taking you to the OR now.", "example": "Alles ist bereit, wir fahren Sie jetzt in den OP." },
    { "id": 132, "category": "Dialoge", "german": "Ist Ihnen schwindelig?", "type": "Satz", "turkish": "Başınız dönüyor mu?", "english": "Do you feel dizzy?", "example": "Setzen Sie sich bitte, ist Ihnen schwindelig?" },
    { "id": 133, "category": "Dialoge", "german": "Bitte bleiben Sie nüchtern.", "type": "Satz", "turkish": "Lütfen aç kalın.", "english": "Please stay fasting.", "example": "Bitte bleiben Sie ab Mitternacht nüchtern." },
    { "id": 134, "category": "Dialoge", "german": "Ziehen Sie bitte den Oberkörper aus.", "type": "Satz", "turkish": "Lütfen üstünüzü soyunun.", "english": "Please take off your top.", "example": "Ziehen Sie bitte den Oberkörper aus für das EKG." },
    { "id": 135, "category": "Dialoge", "german": "Das Bett ist frisch bezogen.", "type": "Satz", "turkish": "Yatak yeni yapıldı.", "english": "The bed is freshly made.", "example": "Legen Sie sich gerne hin, das Bett ist frisch bezogen." },
    { "id": 136, "category": "Dialoge", "german": "Haben Sie eine Patientenverfügung?", "type": "Satz", "turkish": "Hasta vasiyetnameniz var mı?", "english": "Do you have a living will?", "example": "Für die Unterlagen: Haben Sie eine Patientenverfügung?" },
    { "id": 137, "category": "Dialoge", "german": "Brauchen Sie ein Schmerzmittel?", "type": "Satz", "turkish": "Ağrı kesiciye ihtiyacınız var mı?", "english": "Do you need a painkiller?", "example": "Wenn die Schmerzen stark sind, brauchen Sie ein Schmerzmittel?" },
    { "id": 138, "category": "Dialoge", "german": "Wir müssen Sie wiegen.", "type": "Satz", "turkish": "Sizi tartmamız gerekiyor.", "english": "We need to weigh you.", "example": "Kommen Sie bitte mit, wir müssen Sie wiegen." },
    { "id": 139, "category": "Dialoge", "german": "Die Infusion ist fertig.", "type": "Satz", "turkish": "Serum bitti.", "english": "The IV is finished.", "example": "Ich sehe, die Infusion ist fertig. Ich werde sie jetzt entfernen." },
    { "id": 140, "category": "Dialoge", "german": "
